# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'Masonry'
  pod 'AFNetworking','~> 3.2.1'
  
  pod 'FLAnimatedImage'
  pod 'SDWebImage'
#  pod 'SDWebImage/GIF'
  
  pod 'MJRefresh'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'FMDB'
  pod 'Bugly'
  
   #Lite版本(不带实时音视频通话功能)
   pod 'HyphenateLite'
   #Lite版本(带实时音视频通话功能)
#   pod 'Hyphenate'

#   pod 'EaseUILite', :git =>'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

  pod 'mob_sharesdk'
  pod 'mob_sharesdk/ShareSDKUI'
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'  #（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
  pod 'UITableView+FDTemplateLayoutCell' #自适应
  pod 'IQKeyboardManager'  #键盘
  pod 'MJExtension' #模型转换
  pod 'AvoidCrash'                      # 防崩溃
  pod 'SDCycleScrollView'
  pod 'TZImagePickerController'         #上传相册照片
  pod 'HMSegmentedControl'

  pod 'AMap2DMap-NO-IDFA'
  pod 'AMapLocation-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'
  
#  pod 'WechatOpenSDK'
  pod 'AlipaySDK-iOS'           #支付宝
  
  target 'SocialAppTests' do
  inherit! :search_paths
    # Pods for testing
  end

  target 'SocialAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
